site_name: É Crypto
site_url: https://unb-mds.github.io/2025-2-Squad12/
repo_name: unb-mds/2025-2-Squad12
repo_url: https://github.com/unb-mds/2025-2-Squad12

theme:
  name: material
  language: pt-BR


  icon:
    logo: material/currency-btc       
    repo: fontawesome/brands/github   
    previous: material/chevron-left   
    next: material/chevron-right      


  features:
    - navigation.tabs      
    - navigation.footer    
    - navigation.path      
    - search.suggest       
    - search.highlight     
    - content.code.copy    

 
  palette:

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange       
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Mudar para tema escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Mudar para tema claro


plugins:
  - search  

nav:
  - Home: index.md

  - Sprints:
      - Visão Geral: Sprints.md
      - Sprint 0: Sprints/sprint-00.md
      - Sprint 1: Sprints/sprint-01.md
      - Sprint 2: Sprints/sprint-02.md
      - Sprint 3: Sprints/sprint-03.md
      - Sprint 4: Sprints/sprint-04.md
      - Sprint 5: Sprints/sprint-05.md
      - Sprint 6: Sprints/sprint-06.md
      - Sprint 7: Sprints/sprint-07.md
      - Sprint 8: Sprints/sprint-08.md
      - Sprint 9: Sprints/sprint-09.md
      - Sprint 10: Sprints/sprint-10.md
      - Sprint 11: Sprints/sprint-11.md
      - Sprint 12: Sprints/sprint-12.md
      
   - Organização do Projeto:
       - Storymap: storymap.md
       - Roadmap: roadmap.md
       - Como Contribuir?: como-contribuir.md
  #     - Arquitetura: arquitetura.md
  #     - Protótipo: prototipo.md
  #     - Como Executar?: como-executar.md
  #     - Release Notes: release-notes.md


