site_name: É Crypto
site_url: https://unb-mds.github.io/2025-2-Squad12/
repo_name: unb-mds/2025-2-Squad12
repo_url: https://github.com/unb-mds/2025-2-Squad12

theme:
  name: material
  language: pt-BR
  palette:
    - scheme: default        # tema claro
      primary: orange        # barra / links em laranja
      accent: deep orange    # destaques em laranja mais forte
    - scheme: slate          # tema escuro (cinza bem escuro/preto)
      primary: orange
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Mudar para tema claro

nav:
  - Home: index.md
  - Sprints: 
      - Visão Geral: sprints.md
      - Sprint 0: Sprints/sprint-00.md
      - Sprint 1: Sprints/sprint-01.md
      - Sprint 2: Sprints/sprint-02.md
      - Sprint 3: Sprints/sprint-03.md
      - Sprint 4: Sprints/sprint-04.md
      - Sprint 5: Sprints/sprint-05.md
      - Sprint 6: Sprints/sprint-06.md
      - Sprint 7: Sprints/sprint-07.md
      - Sprint 8: Sprints/sprint-08.md
      - Sprint 9: Sprints/sprint-09.md
      - Sprint 10: Sprints/sprint-10.md
      - Sprint 11: Sprints/sprint-11.md
      - Sprint 12: Sprints/sprint-12.md
  - Organização do Projeto:
      - Arquitetura: arquitetura.md
      - Storymap: storymap.md
      - Roadmap: roadmap.md
      - Protótipo: prototipo.md
  - Como Executar?: como-executar.md
  - Como Contribuir?: como-contribuir.md
  - Release Notes: release-notes.md



